### ISSUE TITLE
Hiding list on blur in Firefox

### ISSUE THREAD

**Issue by desjardinsm** [bevacqua/horsey#19] opened 2015-07-31 12:18 UTC
Even when the autoHideOnBlur option is true, tabbing out of an input field that has an autocomplete list open in Firefox will not actually hide the list.  Clicking outside the input, however, hides correctly.

Chrome and IE11 both work as expected.

![4ffesdxzrr](https://cloud.githubusercontent.com/assets/1823844/9007147/87c987de-375c-11e5-8b2a-87420324c972.gif)

**Comment by evaryont** [comment] 2016-01-29 23:53
Noticed this still happening in Firefox 44.

**Comment by XGhozt00** [comment] 2016-02-12 19:27
Also noticed this. Looks like the issue is with line 266 in horsey.js, the "sey-show" class isn't being removed from .sey-list in Firefox for some reason. I ended up just manually running .destroy() and re-creating it as needed, I don't recommend this for performance though.

**Comment by bevacqua** [comment] 2016-07-21 17:24
This is fixed in latest

**Closed by bevacqua** 2016-07-21 17:24 UTC
